language: cpp

os: osx
osx_image: xcode9.2

branches:
  only:
    - master

install:
  - |
    curl "https://www.dropbox.com/s/15s4v2eos5p6fcv/Qt-5.9.3-m13-clang9.tar.xz?dl=1" -L -s | tar xJ
    qtdir=$(ls | grep Qt)
    sudo mv $qtdir /usr/local/
    export PATH="/usr/local/$qtdir/bin:$PATH"

before_script:
  - qmake -config release

script: make
